name: Configure v2

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      configure:
        description: Terraform Backend, Deployment or Both
        type: choice
        default: Both
        options:
        - Backend
        - Deployment
        - Both
      account_id:
        description: "AWS Account Id"
        type: string
      region:
        description: "AWS Region"
        type: string
      role:
        description: "AWS Role"
        type: string


jobs:
  configure:
    uses: stormreply/slt-workflows/.github/workflows/configure-2.yaml@main
    with:
      account_id: ${{ inputs.account_id }}
      configure: ${{ inputs.configure }}
      region: ${{ inputs.region }}
      role: ${{ inputs.role }}
